// @ts-nocheck
// This file is generated by Umi automatically
// DO NOT CHANGE IT MANUALLY!
import HomeOutlined from '/Users/danny.she/react/stripe_payment_merchant_portal/node_modules/@ant-design/icons/es/icons/HomeOutlined';
import SettingOutlined from '/Users/danny.she/react/stripe_payment_merchant_portal/node_modules/@ant-design/icons/es/icons/SettingOutlined';
import TableOutlined from '/Users/danny.she/react/stripe_payment_merchant_portal/node_modules/@ant-design/icons/es/icons/TableOutlined';
import WarningOutlined from '/Users/danny.she/react/stripe_payment_merchant_portal/node_modules/@ant-design/icons/es/icons/WarningOutlined';
import BellOutlined from '/Users/danny.she/react/stripe_payment_merchant_portal/node_modules/@ant-design/icons/es/icons/BellOutlined';
export default { HomeOutlined, SettingOutlined, TableOutlined, WarningOutlined, BellOutlined };
