// @ts-nocheck
// This file is generated by Umi automatically
// DO NOT CHANGE IT MANUALLY!
import React from 'react';

export async function getRoutes() {
  const routes = {"1":{"path":"/user","layout":false,"id":"1"},"2":{"name":"login","path":"/user/login","parentId":"1","id":"2"},"3":{"path":"/welcome","name":"welcome","icon":"home","parentId":"ant-design-pro-layout","id":"3"},"4":{"path":"/payments","name":"payments","icon":"dollar","parentId":"ant-design-pro-layout","id":"4"},"5":{"path":"/settlements","name":"settlements","icon":"transaction","parentId":"ant-design-pro-layout","id":"5"},"6":{"path":"/balances","name":"balances","icon":"wallet","parentId":"ant-design-pro-layout","id":"6"},"7":{"path":"/disputes","name":"disputes","icon":"warning","parentId":"ant-design-pro-layout","id":"7"},"8":{"path":"/message","name":"message","icon":"bell","parentId":"ant-design-pro-layout","id":"8"},"9":{"path":"/developer","name":"developer","hideInMenu":true,"parentId":"ant-design-pro-layout","id":"9"},"10":{"path":"/security","name":"security","hideInMenu":true,"parentId":"ant-design-pro-layout","id":"10"},"11":{"path":"/setting","name":"setting","hideInMenu":true,"parentId":"ant-design-pro-layout","id":"11"},"12":{"path":"/","redirect":"/welcome","parentId":"ant-design-pro-layout","id":"12"},"13":{"path":"*","layout":false,"id":"13"},"ant-design-pro-layout":{"id":"ant-design-pro-layout","path":"/","isLayout":true}} as const;
  return {
    routes,
    routeComponents: {
'1': React.lazy(() => import('./EmptyRoute')),
'2': React.lazy(() => import(/* webpackChunkName: "p__User__Login__index" */'@/pages/User/Login/index.tsx')),
'3': React.lazy(() => import(/* webpackChunkName: "p__Welcome" */'@/pages/Welcome.tsx')),
'4': React.lazy(() => import(/* webpackChunkName: "p__TableList__index" */'@/pages/TableList/index.tsx')),
'5': React.lazy(() => import(/* webpackChunkName: "p__Settlements" */'@/pages/Settlements.tsx')),
'6': React.lazy(() => import(/* webpackChunkName: "p__Balances" */'@/pages/Balances.tsx')),
'7': React.lazy(() => import(/* webpackChunkName: "p__Disputes" */'@/pages/Disputes.tsx')),
'8': React.lazy(() => import(/* webpackChunkName: "p__Message" */'@/pages/Message.tsx')),
'9': React.lazy(() => import(/* webpackChunkName: "p__Developer__index" */'@/pages/Developer/index.tsx')),
'10': React.lazy(() => import(/* webpackChunkName: "p__Security" */'@/pages/Security.tsx')),
'11': React.lazy(() => import(/* webpackChunkName: "p__Setting" */'@/pages/Setting.tsx')),
'12': React.lazy(() => import('./EmptyRoute')),
'13': React.lazy(() => import(/* webpackChunkName: "p__404" */'@/pages/404.tsx')),
'ant-design-pro-layout': React.lazy(() => import(/* webpackChunkName: "t__plugin-layout__Layout" */'/Users/danny.she/react/stripe_payment_merchant_portal/src/.umi-production/plugin-layout/Layout.tsx')),
},
  };
}
